# Generated by Django 4.2.26 on 2025-12-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["project", "-created_at"], name="main_commen_project_f1bdbe_idx"
            ),
        ),
    ]
