# Generated by Django 4.2.26 on 2025-12-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_comment_created_at_alter_tag_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="project",
            name="github_url",
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
